##############################################################################
## Startscript for MUTS logger:
##   Logging data from displacements sensors, phase error and encoder value.
##   No FFT:s.
##   Velocity output on EL4122 (4..20mA)
##
## Hardware:
##   1. One sin/cos 1VPP encoder input
##   2. Four analog inputs for telemess distance sensors
##   3. Timesatmped inputs for phase error calculation
##   Note: Calibration of telemess sensors by use of epics breaktables (bptTypeTelemessCalib_stainless.dbd).
##         The breaktables are used for both ai records and FFT plugins.
##
## Author: Anders Sandström, anders.sandstrom@ess.eu
##

##############################################################################
## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg 7.0.1

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=7.0.1,EC_RATE=1000"

##############################################################################
## Load breaktables with calibration data for Telemess sensors.
require iocshutils 2.10.0  # For updateMenuConvert()
dbLoadRecords ../src/bptTypeTelemessCalib_stainless.dbd
updateMenuConvert
dbDumpBreaktable

##############################################################################
## Configure hardware:
system "ethercat slaves"

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "0")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EK1100"

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "1")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL5021, SUBST_FILE=../db/amo.substitutions"

# Enable reset on c-latch (index track)
ecmcConfigOrDie "Cfg.EcAddSdo($(ECMC_EC_SLAVE_NUM),0x8000,0x1,1,1)"

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "2")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL3174_0to10V, SUBST_FILE=../db/telemessEddyCurrentSensors.substitutions"

# Configure analog sensors common (filter settings valid for all channles)
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL31XX-Sensor-common.cmd

# Example of default configuration of analog sensor CH0
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8000")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3164-Sensor-chX-default.cmd

# Example of default configuration of analog sensor CH1
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8010")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3164-Sensor-chX-default.cmd

# Example of default configuration of analog sensor CH2
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8020")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3164-Sensor-chX-default.cmd

# Example of default configuration of analog sensor CH3
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8030")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3164-Sensor-chX-default.cmd

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "3")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL4122"

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "4")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL9505"

#epicsEnvSet("ECMC_SAMPLE_RATE_MS", 1)
epicsEnvSet("ECMC_EC_SLAVE_NUM",              "5")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL1252"
#epicsEnvSet("ECMC_SAMPLE_RATE_MS", 10)

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

###############################################################################
### PLC 0: For calculating velocity
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=70,FILE=./plc/velo.plc, PLC_MACROS='DBG=#,PLC_ID=0,CYCLE_TIME_S=0.07'")
dbLoadRecords("../db/velo.db","P=$(IOC):,PORT=MC_CPU1,ASYN_NAME=plcs.plc0.static.velo,TSE=-2,T_SMP_MS=1")

##############################################################################
## Cleanup:
epicsEnvUnset(ECMC_FFT_ID)
epicsEnvUnset(ECMC_FFT_NELM)
epicsEnvUnset(ECMC_REVS_TO_FFT)
epicsEnvUnset(ECMC_PLUGIN_CONFIG)
epicsEnvUnset(ECMC_PLUGIN_FILNAME)
epicsEnvUnset(ECMC_ENC_SCALE)

##############################################################################
## Configure diagnostics:
ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

##############################################################################
## go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)
iocInit()

##############################################################################
## Store Records to file
dbl > pvs.log
